services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
  node_app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pg: